### ISSUE TITLE
problem installing package from public github repo

### ISSUE THREAD

**Issue by hems** [heroku/heroku-buildpack-nodejs#760]
I have been trying to have a public github repo as dependency on package.json and although it works locally as expected it fails on heroku.

examples using a branch:
````
"simpleddp": "https://github.com/hems/simpleddp.git#patch-2"
````

example using a commit:
````
"simpleddp": "hems/simpleddp.git#0396884068078c06fbceedc2508cf88bab967b96",
````

i also tried tarball and it did not work.. Eventually on my build on heroku i get the error

`
 Module not found: Can't resolve 'simpleddp' in [...]
`

**Comment by danielleadams** [comment]
Hi @hems, I answered your support ticket, but I'll answer here for visibility too. This should work, but I would use the `git` protocol as suggested in the NPM docs: https://docs.npmjs.com/files/package.json#git-urls-as-dependencies

Regardless of what the issue is, if you're seeing a difference between Heroku and your local machine, my initial guess would be that it is because you have read/write access to the repository via git/GitHub on your local machine. Even though it's a public repository, Heroku will still haven't different access and would receive a 404 when trying to read (assuming that the `Module not found` is the error you're seeing).

I think we could use some supplemental docs regarding using git urls for dependencies, so I'm going to tag this as a documentation. Happy to keep discussing here for transparency or we can continue our discussion via the suppor ticket.

**Comment by hems** [comment]
> Hi @hems, I answered your support ticket, but I'll answer here for visibility too. This should work, but I would use the `git` protocol as suggested in the NPM docs: https://docs.npmjs.com/files/package.json#git-urls-as-dependencies

I just used: 

````json
"simpleddp": "git://github.com/hems/simpleddp.git#patch-2",
````

as you suggested and the error I got in the end was:

````bash
remote: -----> Build failed
````

which is a less than ideal error message.

If i use the regular

````json
"simpleddp": "^2.2.4",
````

It works as expected, so surely the problem is the git url.

> Regardless of what the issue is, if you're seeing a difference between Heroku and your local machine, my initial guess would be that it is because you have read/write access to the repository via git/GitHub on your local machine. Even though it's a public repository, Heroku will still haven't different access 

I don't understand how it would be possible for Heroku to not have access to a public repository on GitHub?

> and would receive a 404 when trying to read (assuming that the `Module not found` is the error you're seeing).

The error I'm seeing is just "Build Failed".

> I think we could use some supplemental docs regarding using git urls for dependencies, so I'm going to tag this as a documentation. Happy to keep discussing here for transparency or we can continue our discussion via the suppor ticket.

Definitely could do with supplemental documentation and also with the actual feature working ( :

**Comment by hems** [comment]
Using the tarball address works on my browser, the package will be downloaded.

for instance https://github.com/hems/simpleddp/tarball/patch-2

But if i use that path on my local package.json it fails when using `node 12.4 / npm 6.9` and also on heroku, the build fails as well, eventually i get the error: 

`remote: Module not found: Can't resolve 'simpleddp' `

**Comment by hems** [comment]
Using `"git://github.com/hems/simpleddp.git#patch-2"` as suggested doesn't work locally for me, also doesn't work on Heroku.

Locally what works for me is:

````json
"simpleddp": "https://github.com/hems/simpleddp.git#patch-2"
````

But pushing that address to Heroku also ends up with "build fails".

````
remote:        src/classes/ddpCollection.js -> lib/classes/ddpCollection.js
remote:        src/classes/ddpEventListener.js -> lib/classes/ddpEventListener.js
remote:        src/classes/ddpOnChange.js -> lib/classes/ddpOnChange.js
remote:        src/classes/ddpReactiveCollection.js -> lib/classes/ddpReactiveCollection.js
remote:        src/classes/ddpReactiveDocument.js -> lib/classes/ddpReactiveDocument.js
remote:        src/classes/ddpReducer.js -> lib/classes/ddpReducer.js
remote:        src/classes/ddpSubscription.js -> lib/classes/ddpSubscription.js
remote:        src/helpers/fullCopy.js -> lib/helpers/fullCopy.js
remote:        src/helpers/isequal.js -> lib/helpers/isequal.js
remote:        src/simpleddp.js -> lib/simpleddp.js
remote: 
remote: -----> Build failed
````

The curious thing is that it actually list the files on Heroku, so it seems it actually can see the files or downloaded the files at some point, but somehow breaks.

The same happens when I use the original repository ( not my fork ), it works locally but yields same error on Heroku.

````js
https://github.com/Gregivy/simpleddp.git
````

But it doesn't when pointing to the original npm package

````js
"simpleddp": "^2.2.4",
````

so it must be a problem on

**Comment by hems** [comment]
I actually just used npm instead of yarn to install via `git://` and it worked locally, but then discovered still did not work on Heroku.

````json
"simpleddp": "git://github.com/hems/simpleddp.git#patch-2"
````

To Heroku i pushed the repo, now with `package.json` and `package-lock.json` as opposed to "package.json" and "yarn.lock", and funny enough Heroku build did not fail, but when I run my project some errors happen, which means something weird during the package installation still going on even though the build succeeded.

I hope this helps to identify the problem and it turns out it's not on my side ( :

**Comment by hems** [comment]
Do you think NODE_MODULES_CACHE might be influencing the outcomes here?

I'm trying now some of those steps again but this time with:
````
heroku config:set NODE_MODULES_CACHE=false
````

**Comment by hems** [comment]
Turns out after a clean slate and properly debugging some of my project that

````json
"simpleddp": "git://github.com/hems/simpleddp.git#patch-2"
````

on the package.json works as expected! thank you

**Comment by hems** [comment]
Also, there is something funny about "yarn" for me, if i use it to install locally it will generate a yarn.lock and when i deploy to heroku the deploy fails.

If i use npm to install and push a package-lock.json to Heroku then the build succeeds.

**Comment by danielleadams** [comment]
@hems do you have a build ID from this output? You can get it from here:

![build-id](https://user-images.githubusercontent.com/6271256/80028465-213ed600-84b3-11ea-9e9d-bc9f8d275d05.png)

I tried running a build both locally and on Heroku with your forked dependency with both https and git protocols, and everything worked, so I'm going to need more information.

From the logs you've pasted, it looks like the build is getting further than install, but I will need the full logs to fully investigate.

**Comment by danielleadams** [comment]
@hems has this issue been resolved?

**Comment by hems** [comment]
> @hems has this issue been resolved?

this was resolved, thank you!

**Comment by cstayyab** [comment]
> Turns out after a clean slate and properly debugging some of my project that
> 
> ```json
> "simpleddp": "git://github.com/hems/simpleddp.git#patch-2"
> ```
> 
> on the package.json works as expected! thank you

This isn't working for me I am still getting the same error. Should I open up a new issue? The repo I am using is a fork and here is its URL: https://github.com/cstayyab/capturl

**Comment by KicksTV** [comment]
I am also running into this issue. 

`"dat.gui": "git://github.com:KicksTV/dat.gui.git",`

but gives me a very long error. Will include what I think is most relavant.

`Installing node modules
remote:        npm ERR! code 1
remote:        npm ERR! git dep preparation failed
remote:        npm ERR! command /tmp/build_33dd61a3/.heroku/node/bin/node /tmp/build_33dd61a3/.heroku/node/lib/node_modules/npm/bin/npm-cli.js install --force --cache=/tmp/npmcache.2vea7 --prefer-offline=false --prefer-online=false --offline=false --no-progress --no-save --no-audit --include=dev --include=peer --include=optional --no-package-lock-only --no-dry-run
remote:        npm ERR! npm ERR! code 1
remote:        npm ERR! npm ERR! path /tmp/npmcache.2vea7/_cacache/tmp/git-cloneBNIhGL/node_modules/node-sass
remote:        npm ERR! npm ERR! command failed
remote:        npm ERR! npm ERR! command sh -c node scripts/build.js`

**Comment by colincasey** [comment]
@cstayyab I had no problem installing your fork of `capturl` using the git url:

```
git://github.com/cstayyab/capturl.git#main
```  

Are you still having this problem?

**Comment by colincasey** [comment]
@KicksTV When using a git url, npm will clone the target dependency locally and run that project's install process.  This means that  `git://github.com:KicksTV/dat.gui.git`, in order to satisfy its dependency on `rollup-plugin-sass`, will attempt to compile [`node-sass@4.13.1`](https://github.com/sass/node-sass/releases/tag/v4.13.1) using `node-gyp` if there are no pre-built versions available.  

That version of `node-sass` only includes pre-built binaries up to node v13 so that is why the `node-gyp` compile process is running.  Modules that compile native addons may fail during Heroku deploy because that environment does not include the necessary C/C++ libraries or the architecture is not supported.
